id = "hackerone-theme"
name = "HackerOne Theme"
version = "0.1.0"
schema_version = 1
authors = ["Sanjaymenon <support+zed@sanjaymenon.xyz>"]
description = "HackerOne Dark and Light Theme, ported from the official VS Code Theme"
repository = "https://github.com/isanjaymenon/hackerone-zed"
